In [ ]:
"""
cv2.imread(),  cv2.imshow(), cv2.namedWindow(), cv2.waitKey(), cv2.destroyWindow(), cv2.destroyAllWindows() 
cv2.imwrite(), img.item(), img.itemset(), cv2.split(), cv2.merge(), img.shape, img.size, img.dtype
cv2.add(), cv2.addWeighted(), cv2.bitwise_and(), cv2.bitwise_or(), cv2.bitwise_xor(), cv2.COLOR_BGR2RGB
cv2.COLOR_BGR2GRAY, cv2.cvtCOLOR(), cv2.resize(), cv2.flip(), cv2.warpAffine(), cv2.getRotationMatrix2D()
cv2.getAffineTransform(), cv2.getPerspectiveTransform(), cv2.warpPerspective(), cv2.threshold()
cv2.THRESH_BINARY, cv2.THRESH_BINARY_INV, cv2.THRESH_TRUNC, cv2.THRESH_TOZERO, cv2.THRESH_TOZERO_INV
cv2.adaptiveThreshold(), cv2.ADAPTIVE_THRESH_MEAN_C, cv2.ADAPTIVE_THRESH_GAUSSIAN_C
cv2.THRESH_OTSU, cv2.blur(), cv2.boxFilter(), cv2.GaussianBlur(), cv2.medianBlur(), cv2.bilateralFilter()
cv2.filter2D(), cv2.erode(), cv2.dilate(), cv2.morphologyEx(), cv2.MORPH_OPEN, cv2.MORPH_CLOSE
cv2.MORPH_GRADIENT, cv2.MORPH_TOPHAT, cv2.MORPH_BLACKHAT, cv2.getStructuringElement(), cv2.MORPH_RECT
cv2.MORPH_CROSS, cv2.MORPH_ELLIPSE, 
"""

In [ ]:
# 第一章
import cv2
cv2.namedWindow('name')
catdog = cv2.imread('catdog.jpg')
cv2.imshow('name', catdog)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import numpy as np
img = np.zeros((3, 3, 3), dtype=np.uint8)
img[:, :, 0]  = 255
print(img)

[[[255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]]]


In [12]:
img1 = np.zeros((3, 3, 3), dtype=np.uint8)
img1[:, 0:1, 0] = 255  # 第一个 : 表示三个 3 X 3 维数组都取
img1[:, 1:2, 1] = 255
img1[:, 2:3, 2] = 255
print(img1)

[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255   0   0]
  [  0 255   0]
  [  0   0 255]]]


In [3]:
a = np.random.randn(3, 3, 3)
a

array([[[ 0.52093971, -0.10393626,  1.01329216],
        [ 0.1766761 , -1.72978313,  0.91837437],
        [-0.29733735, -1.10307678, -0.36755627]],

       [[-0.70421923,  0.60041545,  1.61311229],
        [ 1.03778003,  1.42565125,  1.00936365],
        [-0.30065846,  0.36459496,  0.83182847]],

       [[-0.56079239, -0.57154945,  1.61724847],
        [ 1.0429707 ,  0.05328803,  0.77250672],
        [-0.35525768,  0.5318268 ,  0.51434736]]])

In [6]:
a[:, :, 0], a[:, 0]

(array([[ 0.52093971,  0.1766761 , -0.29733735],
        [-0.70421923,  1.03778003, -0.30065846],
        [-0.56079239,  1.0429707 , -0.35525768]]),
 array([[ 0.52093971, -0.10393626,  1.01329216],
        [-0.70421923,  0.60041545,  1.61311229],
        [-0.56079239, -0.57154945,  1.61724847]]))

In [4]:
import numpy as np
import cv2
a = np.random.randint(0, 255, (3, 3), dtype=np.uint8)
b = np.random.randint(0, 255, (3, 3), dtype=np.uint8)
a, b

(array([[ 89, 242,  32],
        [111,  43,  45],
        [  8, 246, 239]], dtype=uint8),
 array([[ 99, 159, 206],
        [ 82, 223, 200],
        [215,  40, 129]], dtype=uint8))

In [8]:
cv2.bitwise_and(a, b), cv2.bitwise_or(a, b), cv2.bitwise_xor(a, b)

(array([[ 65, 146,   0],
        [ 66,  11,   8],
        [  0,  32, 129]], dtype=uint8),
 array([[123, 255, 238],
        [127, 255, 237],
        [223, 254, 239]], dtype=uint8),
 array([[ 58, 109, 238],
        [ 61, 244, 229],
        [223, 222, 110]], dtype=uint8))

In [10]:
bin(8)

'0b1000'

In [14]:
a = np.random.randint(0, 10, (3, 5, 8))
a

array([[[8, 6, 1, 4, 0, 8, 6, 9],
        [7, 5, 9, 7, 6, 0, 6, 8],
        [1, 4, 8, 4, 0, 3, 6, 6],
        [6, 9, 0, 9, 9, 9, 8, 4],
        [6, 7, 1, 7, 8, 5, 2, 0]],

       [[3, 7, 4, 4, 3, 9, 6, 6],
        [1, 1, 6, 7, 5, 0, 7, 8],
        [0, 8, 5, 2, 3, 1, 5, 3],
        [8, 7, 4, 5, 8, 7, 1, 1],
        [8, 0, 9, 0, 6, 1, 2, 2]],

       [[3, 4, 4, 0, 6, 5, 2, 0],
        [6, 9, 5, 3, 3, 5, 5, 6],
        [3, 7, 9, 8, 8, 4, 6, 1],
        [7, 7, 9, 5, 5, 0, 5, 7],
        [9, 5, 2, 8, 8, 2, 1, 6]]])

In [16]:
for i in range(8):
    a[:, :, i] = 2 ** i
a

array([[[  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128]],

       [[  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128]],

       [[  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128],
        [  1,   2,   4,   8,  16,  32,  64, 128]]])

In [2]:
import cv2
img = cv2.imread('catdog.jpg', 0)
t, rst = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)  # t 代表要返回的阈值，rst 代表阈值结果图像
cv2.imshow('img', img)
cv2.imshow('after_img', rst)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
import cv2
img = cv2.imread('catdog.jpg', 0)
t, rst = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)  # t 代表要返回的阈值，rst 代表阈值结果图像
cv2.imshow('img', img)
cv2.imshow('after_img', rst)
cv2.waitKey()
cv2.destroyAllWindows()