In [1]:
# 1.Tensor 对象及其运算
import numpy as np
import torch

In [7]:
cuda0 = torch.device('cuda:0')

In [8]:
x = torch.ones((2, 2), device = cuda0)
x

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [10]:
x = x.to('cpu')
x.device

device(type='cpu')

In [11]:
a = torch.tensor([[1, 2], 
                  [3, 4]])
torch.clamp(a, min = 2, max = 3)

tensor([[2, 2],
        [3, 3]])

In [12]:
torch.tanh(a)

tensor([[0.7616, 0.9640],
        [0.9951, 0.9993]])

In [13]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [16]:
torch.arange(1, 5, 2)

tensor([1, 3])

In [17]:
torch.range(1, 5 ,2)

<ipython-input-17-bff505b40f43>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1, 5 ,2)


tensor([1., 3., 5.])

In [19]:
torch.linspace(1, 10, 4)

tensor([ 1.,  4.,  7., 10.])

In [20]:
torch.rand(3, 3)

tensor([[0.1884, 0.5706, 0.9821],
        [0.6876, 0.6649, 0.3176],
        [0.6073, 0.9118, 0.6296]])

In [22]:
torch.randn(3, 3)

tensor([[ 2.1522, -1.4575, -0.3936],
        [-0.9410, -0.4581, -0.4098],
        [-0.4754, -0.2370, -0.2410]])

In [24]:
torch.randint(0, 3, (3, 3))

tensor([[2, 0, 0],
        [2, 2, 0],
        [1, 0, 0]])

In [26]:
# 2.Tensor 的索引和切片
a = torch.arange(9).view(3, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [28]:
a[2, 2], a[2][2]

(tensor(8), tensor(8))

In [29]:
a[1:, :-1]

tensor([[3, 4],
        [6, 7]])

In [30]:
a[::2]

tensor([[0, 1, 2],
        [6, 7, 8]])

In [31]:
rows = [1, 0]
cols = [2, 1]
a[rows, cols]

tensor([5, 1])

In [32]:
index = a > 4
index

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [33]:
a[index]

tensor([5, 6, 7, 8])

In [34]:
a = torch.arange(9).view(3, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [37]:
index = torch.nonzero(a >= 7)
index

tensor([[2, 1],
        [2, 2]])

In [38]:
x = torch.randn(3, 3)
y = torch.ones(3, 3)
x, y

(tensor([[-1.1495, -0.7932, -2.1744],
         [ 0.4773,  0.9932, -0.1123],
         [ 0.8170, -1.5580,  1.1074]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [39]:
torch.where(x > 0, x, y)

tensor([[1.0000, 1.0000, 1.0000],
        [0.4773, 0.9932, 1.0000],
        [0.8170, 1.0000, 1.1074]])

In [44]:
# 3.Tensor 的变换，拼接和拆分
a = torch.randn(1, 2, 3, 4, 5)

In [45]:
print('元素个数:', a.nelement())
print('轴的个数:', a.ndimension())
print('矩阵维度:', a.size())

元素个数: 120
轴的个数: 5
矩阵维度: torch.Size([1, 2, 3, 4, 5])


In [46]:
b = a.view(3 * 2, 4 * 5)
b.size()

torch.Size([6, 20])

In [47]:
c = a.reshape(-1)
c.size()

torch.Size([120])

In [48]:
d = a.reshape(6, -1)
d.shape

torch.Size([6, 20])

In [49]:
b = torch.squeeze(a)
b.size()

torch.Size([2, 3, 4, 5])

In [50]:
torch.unsqueeze(b, 0).size()

torch.Size([1, 2, 3, 4, 5])

In [51]:
x = torch.randint(0, 3, (3, 3))
x

tensor([[1, 2, 2],
        [2, 1, 0],
        [1, 0, 0]])

In [52]:
torch.t(x)

tensor([[1, 2, 1],
        [2, 1, 0],
        [2, 0, 0]])

In [55]:
a = torch.ones(1, 2, 3, 4, 5)
b = a.permute(0, 3, 1, 2, 4)
b.size()

torch.Size([1, 4, 2, 3, 5])

In [63]:
x = torch.randn(3, 2)
x

tensor([[0.6794, 0.1926],
        [0.3749, 0.4682],
        [0.6208, 0.9134]])

In [64]:
torch.cat((x, x), 0), torch.cat((x, x), 1)

(tensor([[0.6794, 0.1926],
         [0.3749, 0.4682],
         [0.6208, 0.9134],
         [0.6794, 0.1926],
         [0.3749, 0.4682],
         [0.6208, 0.9134]]),
 tensor([[0.6794, 0.1926, 0.6794, 0.1926],
         [0.3749, 0.4682, 0.3749, 0.4682],
         [0.6208, 0.9134, 0.6208, 0.9134]]))

In [65]:
m = torch.stack((x, x), 0)
n = torch.stack((x, x), 1)
m, n, m.size(), n.size()

(tensor([[[0.6794, 0.1926],
          [0.3749, 0.4682],
          [0.6208, 0.9134]],
 
         [[0.6794, 0.1926],
          [0.3749, 0.4682],
          [0.6208, 0.9134]]]),
 tensor([[[0.6794, 0.1926],
          [0.6794, 0.1926]],
 
         [[0.3749, 0.4682],
          [0.3749, 0.4682]],
 
         [[0.6208, 0.9134],
          [0.6208, 0.9134]]]),
 torch.Size([2, 3, 2]),
 torch.Size([3, 2, 2]))

In [70]:
p = torch.randn(3, 3)
p

tensor([[ 0.6646,  0.7350, -2.0543],
        [ 0.4799,  0.9242,  0.1846],
        [-0.4714,  1.0120,  0.3912]])

In [74]:
torch.stack((p, p), 1)

tensor([[[ 0.6646,  0.7350, -2.0543],
         [ 0.6646,  0.7350, -2.0543]],

        [[ 0.4799,  0.9242,  0.1846],
         [ 0.4799,  0.9242,  0.1846]],

        [[-0.4714,  1.0120,  0.3912],
         [-0.4714,  1.0120,  0.3912]]])

In [75]:
a = torch.randn(10, 3)
a

tensor([[-0.1288, -1.7582,  0.8138],
        [-0.1965,  1.4992,  0.5495],
        [ 0.3504, -0.6369, -0.8550],
        [ 0.4986,  0.1483,  0.7488],
        [ 0.0863, -0.0252,  0.0931],
        [ 0.1404,  0.9335, -0.8195],
        [-0.9292, -0.9113, -0.9422],
        [ 0.8182,  0.3438, -1.3266],
        [ 0.1964, -1.1310, -0.3387],
        [ 1.1701, -0.9363, -0.4493]])

In [77]:
b = torch.split(a, [1, 2, 3, 4], dim = 0)
b

(tensor([[-0.1288, -1.7582,  0.8138]]),
 tensor([[-0.1965,  1.4992,  0.5495],
         [ 0.3504, -0.6369, -0.8550]]),
 tensor([[ 0.4986,  0.1483,  0.7488],
         [ 0.0863, -0.0252,  0.0931],
         [ 0.1404,  0.9335, -0.8195]]),
 tensor([[-0.9292, -0.9113, -0.9422],
         [ 0.8182,  0.3438, -1.3266],
         [ 0.1964, -1.1310, -0.3387],
         [ 1.1701, -0.9363, -0.4493]]))

In [78]:
for i in b:
    print(i.size())

torch.Size([1, 3])
torch.Size([2, 3])
torch.Size([3, 3])
torch.Size([4, 3])


In [82]:
torch.chunk(a, 3, dim = 0), torch.chunk(a, 4, dim = 0)

((tensor([[-0.1288, -1.7582,  0.8138],
          [-0.1965,  1.4992,  0.5495],
          [ 0.3504, -0.6369, -0.8550],
          [ 0.4986,  0.1483,  0.7488]]),
  tensor([[ 0.0863, -0.0252,  0.0931],
          [ 0.1404,  0.9335, -0.8195],
          [-0.9292, -0.9113, -0.9422],
          [ 0.8182,  0.3438, -1.3266]]),
  tensor([[ 0.1964, -1.1310, -0.3387],
          [ 1.1701, -0.9363, -0.4493]])),
 (tensor([[-0.1288, -1.7582,  0.8138],
          [-0.1965,  1.4992,  0.5495],
          [ 0.3504, -0.6369, -0.8550]]),
  tensor([[ 0.4986,  0.1483,  0.7488],
          [ 0.0863, -0.0252,  0.0931],
          [ 0.1404,  0.9335, -0.8195]]),
  tensor([[-0.9292, -0.9113, -0.9422],
          [ 0.8182,  0.3438, -1.3266],
          [ 0.1964, -1.1310, -0.3387]]),
  tensor([[ 1.1701, -0.9363, -0.4493]])))

In [83]:
# 4.PyTorch 的 Reduction 操作
a = torch.randn(3, 3)
a

tensor([[-0.3944, -0.3402, -2.5750],
        [-0.1930,  0.3619,  1.9424],
        [-0.9861, -0.4948,  2.6788]])

In [85]:
torch.max(a), torch.min(a), torch.mean(a)

(tensor(2.6788), tensor(-2.5750), tensor(-3.7389e-05))

In [92]:
torch.median(a, dim = 0), torch.std(a, dim = 0)

(torch.return_types.median(
 values=tensor([-0.3944, -0.3402,  1.9424]),
 indices=tensor([0, 0, 1])),
 tensor([0.4123, 0.4566, 2.8447]))

In [86]:
torch.max(a, dim = 0)

torch.return_types.max(
values=tensor([-0.1930,  0.3619,  2.6788]),
indices=tensor([1, 1, 2]))

In [87]:
torch.cumsum(a, dim = 0)

tensor([[-0.3944, -0.3402, -2.5750],
        [-0.5873,  0.0217, -0.6326],
        [-1.5735, -0.4730,  2.0462]])

In [89]:
torch.cumprod(a, dim = 0)

tensor([[ -0.3944,  -0.3402,  -2.5750],
        [  0.0761,  -0.1231,  -5.0018],
        [ -0.0750,   0.0609, -13.3988]])

In [94]:
a = torch.randint(0, 4, (3, 3))
a, torch.unique(a)  # 查看 a 中出现了哪些元素

(tensor([[1, 1, 0],
         [0, 1, 1],
         [0, 3, 1]]),
 tensor([0, 1, 3]))

In [99]:
# 5. PyTorch 的自动微分
x = torch.arange(9).view(3, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [101]:
x.requires_grad

False

In [102]:
x = torch.rand(3, 3, requires_grad = True)
x

tensor([[0.8761, 0.5334, 0.6888],
        [0.5440, 0.2358, 0.1977],
        [0.8704, 0.2128, 0.2522]], requires_grad=True)

In [120]:
x = torch.rand(3, 3, requires_grad = True)
w = torch.ones(3, 3, requires_grad = True)
x, w

(tensor([[0.5906, 0.2927, 0.9980],
         [0.6802, 0.9616, 0.7321],
         [0.1826, 0.9461, 0.3418]], requires_grad=True),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]], requires_grad=True))

In [121]:
yy = torch.mm(x, w)
yy

tensor([[1.8813, 1.8813, 1.8813],
        [2.3739, 2.3739, 2.3739],
        [1.4706, 1.4706, 1.4706]], grad_fn=<MmBackward>)

In [122]:
detach_yy = yy.detach()
y = torch.mean(yy)
y

tensor(1.9086, grad_fn=<MeanBackward0>)

In [123]:
print(y.backward())

None


In [124]:
w.grad

tensor([[0.1615, 0.1615, 0.1615],
        [0.2445, 0.2445, 0.2445],
        [0.2302, 0.2302, 0.2302]])

In [125]:
x.grad

tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])

In [127]:
y = torch.sum(torch.mm(w, x))
print(y.requires_grad)

True


In [128]:
with torch.no_grad():  # 包括的代码段不会计算微分
    y = torch.sum(torch.mm(w, x))
    print(y.requires_grad)

False
